import * as THREE from "three";
import { makePoringTexture } from "./textures.js";

export type MonsterArch = "jelly" | "bug" | "beast" | "undead" | "plant" | "rock" | "demon" | "bird" | "ghost" | "dragon" | "golem" | "aquatic" | "humanoid";

export interface MonsterAppearance {
  arch: MonsterArch;
  texture: THREE.Texture; // jelly face (also a fallback)
  main: number; // primary toon colour
  accent: number; // secondary toon colour
  scale: number;
  boss?: boolean;
}

interface AppearanceDef {
  inner: string;
  outer: string;
  scale: number;
  boss?: boolean;
}

// Visual family per template — drives which low-poly mesh archetype is built.
const ARCH: Record<string, MonsterArch> = {
  poring: "jelly", drops: "jelly", lunatic: "jelly", angeling: "jelly",
  fabre: "bug", chonchon: "bug", stem_worm: "bug", metaling: "bug", venatu: "bug", sleeper: "bug",
  wolf: "beast", coco: "beast", eddga: "beast", kraken: "aquatic",
  zombie: "undead", skeleton: "undead", wraith: "undead", gargoyle: "undead", vanberk: "undead", hodremlin: "undead", amon_ra: "undead",
  spore: "plant", dryad: "plant", tendrilion: "plant",
  hardrock_mammoth: "golem", clock: "rock", clock_tower_manager: "golem", sandman: "rock", anolian: "aquatic",
  tao_gunka: "golem", ktullanux: "golem",
  baphomet: "demon", dark_lord: "demon", beelzebub: "demon", gloom: "demon", thanatos_phantom: "demon", memory_of_thanatos: "demon",
  hill_wind: "bird", owl_duke: "bird", vesper: "bird", valkyrie_randgris: "bird", kiel: "bird",
  moonlight: "ghost", mistress: "ghost", punk: "ghost", aliot: "ghost", aliza: "ghost",
  anubis: "undead", pasana: "undead", drake: "undead", egnigem: "undead",
  satan_morroc: "demon", nidhoggr: "demon", kathryne: "ghost",
  cecil: "bird", wickebine: "bug", ferus: "dragon", acidus: "dragon", detale: "dragon", boitata: "dragon",
  marionette: "ghost", nightmare: "beast", marduk: "bug", doppelganger: "demon", dark_priest: "ghost",
  loli_ruri: "ghost", quve: "ghost", gibbet: "undead", bacsojin: "ghost", fallen_bishop: "demon",
  poison_spore: "plant", karakasa: "ghost", tengu: "demon", samurai_specter: "undead", kapha: "aquatic",
  cookie: "jelly", myst_case: "rock", antonio: "beast", stormy_knight: "undead", garm: "beast",
  kobold: "humanoid", elder_willow: "plant", brilight: "bug", lady_tanee: "plant", leak: "dragon",
  les: "beast", mavka: "plant", uzhas: "undead", gopinich: "demon", baba_yaga: "ghost",
  magmaring: "jelly", kasa: "demon", salamander: "dragon", gigantes: "golem", ifrit: "demon",
  marc: "aquatic", vadon: "aquatic", kukre: "bug", phreeoni: "beast", deviace: "aquatic",
  orc_warrior: "humanoid", orc_archer: "humanoid", orc_zombie: "undead", orc_lord: "humanoid", orc_hero: "humanoid",
  raydric: "undead", khalitzburg: "humanoid", evil_druid: "plant", abysmal_knight: "humanoid", amdarais: "demon",
  mummy: "undead", matyr: "beast", minorous: "humanoid", pharaoh: "demon", osiris: "undead",
  pupa: "bug", roda_frog: "beast", thief_bug: "bug", creamy: "bird", willow: "plant",
  solid_skull: "undead", assaulter: "beast", permeter: "golem", freezer: "aquatic", turtle_general: "golem",
  increase_soil: "golem", mao_guai: "demon", zhu_po_long: "dragon", chung_e: "humanoid", evil_snake_lord: "dragon",
  bloody_knight: "humanoid", wanderer: "undead", owl_baron: "bird", dark_illusion: "ghost", corrupt_monk: "demon",
  ronin: "humanoid", shrine_spirit: "ghost", stone_lion: "golem", jade_warlord: "humanoid", spirit_empress: "ghost",
  miming: "plant", pom_spider: "bug", luciola_vespa: "bug", bangungot: "ghost", bungisngis: "humanoid",
  piranha: "aquatic", curupira: "plant", iara: "ghost", jaguar_king: "beast", anaconda: "dragon",
  dustiness: "bug", hode: "beast", galapago: "beast", gold_acidus: "dragon", tatacho: "beast",
  scaraba: "bug", dolomedes: "bug", centipede: "bug", queen_scaraba: "bug", kublin: "demon",
  snowier: "jelly", gazeti: "bird", siroma: "aquatic", frost_giant: "golem", ice_queen: "ghost",
  banaspaty: "demon", butoijo: "jelly", kaho: "beast", leyak: "ghost", rangda: "demon",
  tiyanak: "demon", hilsrion: "golem", naga: "dragon", gioia: "humanoid", kades: "demon",
  cornus: "bird", faceworm: "dragon", pinguicula: "plant", wakwak: "humanoid", faceworm_queen: "dragon",
  sentinel: "golem", drone: "bug", scout_bot: "bird", war_machine: "golem", overlord_core: "demon",
  mudskipper: "aquatic", horseshoe_crab: "aquatic", smooth_otter: "beast", sea_serpent: "dragon", the_merlion: "aquatic",
  macaque: "beast", pangolin: "beast", hornbill: "bird", king_macaque: "humanoid", reticulated_python: "dragon",
  jiangshi: "undead", street_cat: "beast", lantern_wisp: "ghost", jiangshi_lord: "undead", nian_beast: "beast",
  supertree_sprite: "plant", firefly_swarm: "bug", orchid_fae: "plant", supertree_guardian: "golem", flower_dome_titan: "golem",
  pontianak: "ghost", orang_minyak: "demon", hantu_air: "ghost", pontianak_queen: "ghost", penanggalan: "demon",
  otter_alpha: "beast", giant_grouper: "aquatic", resort_peacock: "bird", sentosa_merlion: "aquatic", leviathan: "dragon",
  bugis_corsair: "humanoid", djinn: "demon", batik_serpent: "dragon", sultan_jinn: "demon", naga_emas: "dragon",
  chrome_sentry: "golem", neon_wisp: "ghost", drone_swarm: "bug", skyline_colossus: "golem", spectra_dragon: "dragon",
  lab_slime: "jelly", raptor: "beast", pterodactyl: "bird", t_rex: "dragon", mecha_dino: "golem",
  wild_boar: "beast", kampong_rooster: "bird", mangrove_crab: "aquatic", boar_king: "beast", mangrove_naga: "dragon",
  hell_judge: "undead", ox_head: "humanoid", horse_face: "humanoid", yama_king: "demon", tiger_spirit: "beast",
  beach_crab: "aquatic", seagull: "bird", sand_flea: "bug", giant_stingray: "aquatic", tidal_kraken: "aquatic",
  spice_sprite: "plant", war_ghost: "ghost", bunker_sentry: "golem", colonial_wraith: "ghost", hill_sentinel: "golem",
  cable_wraith: "ghost", peak_eagle: "bird", stone_golem: "golem", faber_titan: "golem", wind_djinn: "demon",
  pow_spirit: "ghost", beach_ghoul: "undead", jewel_drone: "golem", changi_revenant: "ghost", vortex_guardian: "golem",
  water_monitor: "beast", treetop_colugo: "bird", swamp_leech: "bug", treetop_warden: "plant", reservoir_naga: "dragon",
  festival_effigy: "golem", deepavali_wisp: "ghost", saree_serpent: "dragon", kali_avatar: "demon", gopuram_guardian: "golem",
  mall_mannequin: "humanoid", neon_phantom: "ghost", holo_serpent: "dragon", ion_colossus: "golem", orchard_specter: "demon",
  wetland_heron: "bird", fiddler_crab: "aquatic", marsh_terrapin: "beast", estuarine_titan: "beast", garuda_matriarch: "bird",
  night_panther: "beast", giant_flying_fox: "bird", moonlit_moth: "bug", malayan_tiger_lord: "beast", mandai_naga: "dragon",
  temple_tortoise: "beast", shrine_carp: "aquatic", pilgrim_wisp: "ghost", kusu_tortoise_god: "beast", wishing_well_naga: "dragon",
  garden_swan: "bird", orchid_sprite: "plant", koi_spirit: "aquatic", bandstand_golem: "golem", swan_lake_naga: "dragon",
  battery_phantom: "ghost", reef_lobster: "aquatic", cliff_bat: "bird", coastal_gun_golem: "golem", dragon_teeth_wraith: "ghost",
  coney_bull: "beast", casuarina_sprite: "plant", mudflat_crane: "bird", white_bull_king: "beast", driftwood_treant: "plant",
  kopitiam_spirit: "ghost", songbird_swarm: "bird", back_alley_rat: "beast", art_deco_golem: "golem", market_wraith: "ghost",
  kelong_crab: "aquatic", lalang_sprite: "plant", waterway_egret: "bird", sand_quarry_golem: "golem", tilapia_titan: "aquatic",
  sandcastle_crab: "aquatic", park_squirrel: "beast", kite_wisp: "ghost", mangrove_monitor: "beast", hedge_maze_golem: "golem",
  turbine_sentinel: "golem", spillway_wraith: "ghost", surge_elemental: "aquatic", barrage_leviathan: "aquatic", tempest_dragon: "dragon",
};

function hex(s: string): number {
  return parseInt(s.replace("#", ""), 16);
}

// Per-template look. Same jelly art, recoloured + rescaled per species.
const DEFS: Record<string, AppearanceDef> = {
  poring: { inner: "#ffd1e6", outer: "#ff9ec4", scale: 1 },
  fabre: { inner: "#fff0c0", outer: "#e7c64a", scale: 0.85 },
  drops: { inner: "#d8f6cb", outer: "#82cf63", scale: 1 },
  lunatic: { inner: "#ffffff", outer: "#d7d7de", scale: 0.95 },
  poring_king: { inner: "#ffe7a0", outer: "#e3b400", scale: 2.2, boss: true },
  spore: { inner: "#d8b0e0", outer: "#7a4a86", scale: 0.95 },
  wolf: { inner: "#c9c9d2", outer: "#6b6b76", scale: 1.25 },
  zombie: { inner: "#b6c79a", outer: "#5c7a44", scale: 1.15 },
  skeleton: { inner: "#f0f0f0", outer: "#b8b8c0", scale: 1.2 },
  baphomet: { inner: "#b03030", outer: "#3a0d12", scale: 2.6, boss: true },
  punk: { inner: "#e0b0e8", outer: "#7a3a86", scale: 1.05 },
  clock: { inner: "#d8c088", outer: "#7a5a28", scale: 1.35 },
  clock_tower_manager: { inner: "#e0c060", outer: "#3a2c10", scale: 2.8, boss: true },
  sandman: { inner: "#e8d49a", outer: "#9a7a40", scale: 1.3 },
  anolian: { inner: "#9ad0c0", outer: "#3a7a68", scale: 1.35 },
  dryad: { inner: "#a8d088", outer: "#3a6a2c", scale: 1.4 },
  stem_worm: { inner: "#d0e090", outer: "#6a8a30", scale: 1.3 },
  hardrock_mammoth: { inner: "#9a7050", outer: "#3a281c", scale: 3, boss: true },
  wraith: { inner: "#cfe0f0", outer: "#5a6e90", scale: 1.2 },
  gargoyle: { inner: "#b8b0a0", outer: "#5c5448", scale: 1.4 },
  dark_lord: { inner: "#7a3aa0", outer: "#14081e", scale: 3, boss: true },
  // extra regulars
  chonchon: { inner: "#d8e088", outer: "#7a8a30", scale: 0.8 },
  coco: { inner: "#d8b088", outer: "#7a5430", scale: 0.95 },
  // 2nd bosses + Payon/Comodo bosses
  angeling: { inner: "#fff0b0", outer: "#e0b840", scale: 2, boss: true },
  eddga: { inner: "#e0a040", outer: "#5a2c10", scale: 2.4, boss: true },
  moonlight: { inner: "#f0c0e0", outer: "#7a3a86", scale: 2.2, boss: true },
  mistress: { inner: "#f0d060", outer: "#6a4a10", scale: 2.2, boss: true },
  amon_ra: { inner: "#e0c060", outer: "#3a2c10", scale: 2.6, boss: true },
  owl_duke: { inner: "#d0c0a0", outer: "#4a3c28", scale: 2.6, boss: true },
  kraken: { inner: "#6aa0c0", outer: "#10384a", scale: 2.8, boss: true },
  tao_gunka: { inner: "#9a7050", outer: "#2a180c", scale: 3, boss: true },
  gloom: { inner: "#9a9ad0", outer: "#1a1430", scale: 2.8, boss: true },
  valkyrie_randgris: { inner: "#f0f0d0", outer: "#b0a050", scale: 3, boss: true },
  // Juno
  sleeper: { inner: "#f0d8a0", outer: "#9a7a40", scale: 1.2 },
  hill_wind: { inner: "#c0e0f0", outer: "#4a7a9a", scale: 1.25 },
  kiel: { inner: "#e0e0e0", outer: "#6a6a78", scale: 2.8, boss: true },
  vesper: { inner: "#d0d0e8", outer: "#3a3a5a", scale: 3, boss: true },
  // Einbroch
  metaling: { inner: "#c0c0c8", outer: "#5a5a60", scale: 1.2 },
  venatu: { inner: "#a0c8b0", outer: "#3a6a4a", scale: 1.3 },
  boitata: { inner: "#e08040", outer: "#3a1808", scale: 3, boss: true },
  tendrilion: { inner: "#90d070", outer: "#2a5a1a", scale: 2.9, boss: true },
  // Rachel
  vanberk: { inner: "#e0a0a0", outer: "#7a2c2c", scale: 1.3 },
  hodremlin: { inner: "#c0b0e0", outer: "#4a3a7a", scale: 1.35 },
  ktullanux: { inner: "#c0e0f0", outer: "#2a5a7a", scale: 3, boss: true },
  beelzebub: { inner: "#8a3aa0", outer: "#100818", scale: 3.2, boss: true },
  // Thanatos Tower
  aliot: { inner: "#c0a0d0", outer: "#5a3a6a", scale: 1.3 },
  aliza: { inner: "#d0a0c0", outer: "#6a3a5a", scale: 1.3 },
  thanatos_phantom: { inner: "#d04060", outer: "#2a0810", scale: 3, boss: true },
  memory_of_thanatos: { inner: "#ff4060", outer: "#1a0008", scale: 3.4, boss: true },
  // Morocc
  anubis: { inner: "#e0c060", outer: "#3a2c10", scale: 1.4 },
  pasana: { inner: "#e8d8a0", outer: "#8a6a30", scale: 1.35 },
  drake: { inner: "#9ab0c0", outer: "#1a3040", scale: 2.9, boss: true },
  satan_morroc: { inner: "#d04030", outer: "#2a0808", scale: 3.4, boss: true },
  // Bio Lab
  cecil: { inner: "#d0c0a0", outer: "#5a4a30", scale: 1.3 },
  wickebine: { inner: "#c0a0d0", outer: "#4a2a5a", scale: 1.25 },
  egnigem: { inner: "#c0c8d0", outer: "#3a4450", scale: 2.8, boss: true },
  kathryne: { inner: "#e0c0f0", outer: "#4a2a6a", scale: 2.9, boss: true },
  // Abyss
  ferus: { inner: "#e07050", outer: "#5a1808", scale: 1.5 },
  acidus: { inner: "#80c0d0", outer: "#1a4a5a", scale: 1.5 },
  detale: { inner: "#f08040", outer: "#3a1004", scale: 3.4, boss: true },
  nidhoggr: { inner: "#9a4fb0", outer: "#100818", scale: 3.6, boss: true },
  // Geffen Tower
  marionette: { inner: "#e0c0e0", outer: "#6a3a6a", scale: 1.2 },
  nightmare: { inner: "#9a90c0", outer: "#2a2440", scale: 1.4 },
  marduk: { inner: "#d0c060", outer: "#6a5a10", scale: 1.25 },
  doppelganger: { inner: "#9a9ad0", outer: "#1a1430", scale: 2.6, boss: true },
  dark_priest: { inner: "#d0b0e0", outer: "#3a2050", scale: 2.6, boss: true },
  // Niflheim
  loli_ruri: { inner: "#cfe0e8", outer: "#5a6a78", scale: 1.2 },
  quve: { inner: "#c0d0d8", outer: "#48565e", scale: 1.25 },
  gibbet: { inner: "#d8d0b0", outer: "#5a4a30", scale: 1.4 },
  bacsojin: { inner: "#eaf0f4", outer: "#7a8a96", scale: 2.8, boss: true },
  fallen_bishop: { inner: "#d0b0d0", outer: "#2a1830", scale: 3, boss: true },
  // Amatsu
  poison_spore: { inner: "#b0d088", outer: "#4a6a28", scale: 1.1 },
  karakasa: { inner: "#e0d0c0", outer: "#8a3030", scale: 1.3 },
  tengu: { inner: "#e09090", outer: "#7a2424", scale: 1.45 },
  samurai_specter: { inner: "#c0c8d0", outer: "#2a3038", scale: 2.6, boss: true },
  kapha: { inner: "#9ad0c8", outer: "#2a5a54", scale: 2.7, boss: true },
  // Lutie
  cookie: { inner: "#f0e0c0", outer: "#b08a50", scale: 0.95 },
  myst_case: { inner: "#e0b0b0", outer: "#8a3030", scale: 1.2 },
  antonio: { inner: "#f0c0c0", outer: "#a83030", scale: 1.2 },
  stormy_knight: { inner: "#cfe0f0", outer: "#3a5a8a", scale: 2.6, boss: true },
  garm: { inner: "#e0f0f8", outer: "#5a8ab0", scale: 2.9, boss: true },
  // Ayothaya
  kobold: { inner: "#e0a060", outer: "#7a3a18", scale: 1.2 },
  elder_willow: { inner: "#b0d080", outer: "#3a6a28", scale: 1.4 },
  brilight: { inner: "#d0e060", outer: "#5a7a20", scale: 1.0 },
  lady_tanee: { inner: "#a8d088", outer: "#3a6a2c", scale: 2.9, boss: true },
  leak: { inner: "#80c0a0", outer: "#1a5a44", scale: 3, boss: true },
  // Moscovia
  les: { inner: "#c0a070", outer: "#6a4a28", scale: 1.3 },
  mavka: { inner: "#c0e090", outer: "#4a7a30", scale: 1.25 },
  uzhas: { inner: "#a0b0c0", outer: "#3a4450", scale: 1.4 },
  gopinich: { inner: "#e08050", outer: "#5a2010", scale: 2.9, boss: true },
  baba_yaga: { inner: "#c0b0a0", outer: "#4a3a28", scale: 2.7, boss: true },
  // Thor Volcano
  magmaring: { inner: "#ffb060", outer: "#a83010", scale: 1.0 },
  kasa: { inner: "#ff9050", outer: "#7a2008", scale: 1.3 },
  salamander: { inner: "#ff8040", outer: "#6a1804", scale: 1.5 },
  gigantes: { inner: "#d09060", outer: "#5a2810", scale: 3.1, boss: true },
  ifrit: { inner: "#ff7030", outer: "#5a0c04", scale: 3.4, boss: true },
  // Byalan
  marc: { inner: "#a0d0e0", outer: "#2a6a8a", scale: 1.0 },
  vadon: { inner: "#e0a090", outer: "#8a3020", scale: 1.1 },
  kukre: { inner: "#d0c080", outer: "#6a5a20", scale: 0.95 },
  phreeoni: { inner: "#d0b080", outer: "#6a4a20", scale: 2.5, boss: true },
  deviace: { inner: "#a0c0e0", outer: "#2a4a7a", scale: 2.6, boss: true },
  // Orc Village
  orc_warrior: { inner: "#a0c070", outer: "#4a5a28", scale: 1.35 },
  orc_archer: { inner: "#b0c080", outer: "#5a6a30", scale: 1.3 },
  orc_zombie: { inner: "#90a070", outer: "#3a4a28", scale: 1.4 },
  orc_lord: { inner: "#a0b060", outer: "#3a4a18", scale: 2.7, boss: true },
  orc_hero: { inner: "#c08050", outer: "#5a2810", scale: 2.8, boss: true },
  // Glast Heim Churchyard
  raydric: { inner: "#a0a0b0", outer: "#2a2a3a", scale: 1.35 },
  khalitzburg: { inner: "#c0c8d8", outer: "#3a4a6a", scale: 1.4 },
  evil_druid: { inner: "#a0c090", outer: "#3a5a30", scale: 1.35 },
  abysmal_knight: { inner: "#b0b0c0", outer: "#2a2a44", scale: 2.7, boss: true },
  amdarais: { inner: "#c04060", outer: "#2a0810", scale: 2.9, boss: true },
  // Pyramid
  mummy: { inner: "#e0d8b0", outer: "#8a7440", scale: 1.35 },
  matyr: { inner: "#c0a070", outer: "#5a3a18", scale: 1.2 },
  minorous: { inner: "#c08060", outer: "#5a2818", scale: 1.5 },
  pharaoh: { inner: "#e0c060", outer: "#5a4010", scale: 2.8, boss: true },
  osiris: { inner: "#e0d090", outer: "#6a5418", scale: 2.9, boss: true },
  // extra early regulars
  pupa: { inner: "#f0d8a0", outer: "#b08840", scale: 0.8 },
  roda_frog: { inner: "#a8d088", outer: "#3a7a3a", scale: 0.95 },
  thief_bug: { inner: "#b0b0c0", outer: "#3a3a4a", scale: 0.85 },
  creamy: { inner: "#ffd8e0", outer: "#e08aa8", scale: 0.9 },
  willow: { inner: "#c0e090", outer: "#5a7a30", scale: 1.0 },
  // Turtle Island
  solid_skull: { inner: "#dcdce4", outer: "#5a5a6a", scale: 1.3 },
  assaulter: { inner: "#c0a070", outer: "#5a3a18", scale: 1.35 },
  permeter: { inner: "#90b0a0", outer: "#3a5a4a", scale: 1.4 },
  freezer: { inner: "#a0d0e0", outer: "#2a6a8a", scale: 2.7, boss: true },
  turtle_general: { inner: "#8ac090", outer: "#2a5a34", scale: 3.0, boss: true },
  // Louyang
  increase_soil: { inner: "#c0a878", outer: "#5a4424", scale: 1.35 },
  mao_guai: { inner: "#d0a0c0", outer: "#5a2a4a", scale: 1.3 },
  zhu_po_long: { inner: "#e0c060", outer: "#7a5418", scale: 1.5 },
  chung_e: { inner: "#f0c0d0", outer: "#a83050", scale: 2.7, boss: true },
  evil_snake_lord: { inner: "#80c890", outer: "#1a5a34", scale: 3.1, boss: true },
  // Glast Heim Abyss
  bloody_knight: { inner: "#d06060", outer: "#5a1818", scale: 1.45 },
  wanderer: { inner: "#a0a0b0", outer: "#2a2a38", scale: 1.4 },
  owl_baron: { inner: "#c0b090", outer: "#4a3c28", scale: 1.4 },
  dark_illusion: { inner: "#a070c0", outer: "#1a0a2a", scale: 2.9, boss: true },
  corrupt_monk: { inner: "#d0b0c0", outer: "#2a1828", scale: 3.0, boss: true },
  // Gonryun Shrine
  ronin: { inner: "#d0c0a0", outer: "#5a4a30", scale: 1.35 },
  shrine_spirit: { inner: "#cfe0e8", outer: "#5a7a8a", scale: 1.25 },
  stone_lion: { inner: "#c8b088", outer: "#5a4830", scale: 1.45 },
  jade_warlord: { inner: "#a0d0a0", outer: "#2a5a34", scale: 2.8, boss: true },
  spirit_empress: { inner: "#f0d8e8", outer: "#8a4a7a", scale: 2.8, boss: true },
  // Bifrost
  miming: { inner: "#d0e0a0", outer: "#5a7a40", scale: 1.2 },
  pom_spider: { inner: "#c0b0d0", outer: "#4a3a5a", scale: 1.2 },
  luciola_vespa: { inner: "#f0e060", outer: "#7a6010", scale: 1.1 },
  bangungot: { inner: "#b0a0d0", outer: "#3a2a5a", scale: 2.8, boss: true },
  bungisngis: { inner: "#d0c090", outer: "#5a4828", scale: 3.0, boss: true },
  // Brasilis
  piranha: { inner: "#d0a060", outer: "#6a3018", scale: 1.0 },
  curupira: { inner: "#c0e080", outer: "#4a7a28", scale: 1.2 },
  iara: { inner: "#a0d0e0", outer: "#2a6a8a", scale: 1.3 },
  jaguar_king: { inner: "#e0c060", outer: "#6a4818", scale: 2.7, boss: true },
  anaconda: { inner: "#90c070", outer: "#2a5a28", scale: 3.0, boss: true },
  // Veins Canyon
  dustiness: { inner: "#e0d0a0", outer: "#8a7040", scale: 1.0 },
  hode: { inner: "#d0b080", outer: "#6a4a28", scale: 1.2 },
  galapago: { inner: "#c8a878", outer: "#5a4424", scale: 1.3 },
  gold_acidus: { inner: "#f0d060", outer: "#7a5a10", scale: 2.8, boss: true },
  tatacho: { inner: "#a0c0d0", outer: "#3a5a6a", scale: 3.0, boss: true },
  // Scaraba Hole
  scaraba: { inner: "#b0a060", outer: "#4a3a18", scale: 1.2 },
  dolomedes: { inner: "#a0b0c0", outer: "#3a4a5a", scale: 1.25 },
  centipede: { inner: "#c08060", outer: "#5a2818", scale: 1.3 },
  queen_scaraba: { inner: "#d0c060", outer: "#5a4a18", scale: 3.0, boss: true },
  kublin: { inner: "#e09050", outer: "#5a2010", scale: 3.1, boss: true },
  // Ice Cave
  snowier: { inner: "#e8f4fa", outer: "#9ac0d8", scale: 1.0 },
  gazeti: { inner: "#d0e8f4", outer: "#5a8ab0", scale: 1.25 },
  siroma: { inner: "#bfe0ec", outer: "#3a7a9a", scale: 1.15 },
  frost_giant: { inner: "#cfe8f4", outer: "#4a7a9a", scale: 3.1, boss: true },
  ice_queen: { inner: "#eaf4fa", outer: "#7a9ac0", scale: 2.8, boss: true },
  // Dewata
  banaspaty: { inner: "#ffb060", outer: "#7a3010", scale: 1.2 },
  butoijo: { inner: "#c0e0d0", outer: "#3a7a6a", scale: 1.1 },
  kaho: { inner: "#e09060", outer: "#6a2810", scale: 1.3 },
  leyak: { inner: "#d0c0d0", outer: "#4a2a4a", scale: 2.7, boss: true },
  rangda: { inner: "#e0b0a0", outer: "#5a2818", scale: 2.9, boss: true },
  // Splendide
  tiyanak: { inner: "#c0a0d0", outer: "#4a2a6a", scale: 1.2 },
  hilsrion: { inner: "#c0b088", outer: "#5a4a28", scale: 1.4 },
  naga: { inner: "#80c0a0", outer: "#1a5a44", scale: 1.5 },
  gioia: { inner: "#f0e0a0", outer: "#8a7030", scale: 2.8, boss: true },
  kades: { inner: "#a070c0", outer: "#1a0a2a", scale: 3.0, boss: true },
  // Eclage
  cornus: { inner: "#cfe8f0", outer: "#5a8a9a", scale: 1.3 },
  faceworm: { inner: "#d0b070", outer: "#6a4a18", scale: 1.4 },
  pinguicula: { inner: "#b0e090", outer: "#3a7a28", scale: 1.2 },
  wakwak: { inner: "#c0d090", outer: "#4a6a28", scale: 2.8, boss: true },
  faceworm_queen: { inner: "#e0c060", outer: "#6a4a10", scale: 3.2, boss: true },
  // Manuk Fortress
  sentinel: { inner: "#a0b0c0", outer: "#3a4450", scale: 1.4 },
  drone: { inner: "#c0c0a0", outer: "#5a5a3a", scale: 1.0 },
  scout_bot: { inner: "#b0c0d0", outer: "#3a4a5a", scale: 1.2 },
  war_machine: { inner: "#c08060", outer: "#4a2818", scale: 3.1, boss: true },
  overlord_core: { inner: "#c060a0", outer: "#2a0a1a", scale: 3.0, boss: true },
  // Merlion Bay (Singapore)
  mudskipper: { inner: "#c0b070", outer: "#5a4a28", scale: 0.95 },
  horseshoe_crab: { inner: "#a08060", outer: "#4a3018", scale: 1.1 },
  smooth_otter: { inner: "#b08860", outer: "#5a3a20", scale: 1.0 },
  sea_serpent: { inner: "#70c0c0", outer: "#1a5a5a", scale: 2.7, boss: true },
  the_merlion: { inner: "#f0e0a0", outer: "#b08040", scale: 3.0, boss: true },
  // Bukit Timah (Singapore)
  macaque: { inner: "#c0a880", outer: "#5a4428", scale: 1.0 },
  pangolin: { inner: "#c0a070", outer: "#5a4020", scale: 1.1 },
  hornbill: { inner: "#e0d040", outer: "#3a2a10", scale: 1.2 },
  king_macaque: { inner: "#d0b888", outer: "#6a4a28", scale: 2.7, boss: true },
  reticulated_python: { inner: "#c0b060", outer: "#4a3a18", scale: 2.9, boss: true },
  // Chinatown (Singapore)
  jiangshi: { inner: "#a0c0b0", outer: "#3a5a4a", scale: 1.3 },
  street_cat: { inner: "#d0b090", outer: "#5a4030", scale: 0.9 },
  lantern_wisp: { inner: "#ffd070", outer: "#c04020", scale: 1.1 },
  jiangshi_lord: { inner: "#b0d0c0", outer: "#2a5a4a", scale: 2.7, boss: true },
  nian_beast: { inner: "#e0a040", outer: "#7a2820", scale: 2.9, boss: true },
  // Gardens by the Bay (Singapore)
  supertree_sprite: { inner: "#b0e080", outer: "#3a7a28", scale: 1.2 },
  firefly_swarm: { inner: "#f0e060", outer: "#7a6010", scale: 0.9 },
  orchid_fae: { inner: "#f0a0d0", outer: "#8a3060", scale: 1.1 },
  supertree_guardian: { inner: "#90c060", outer: "#2a5a20", scale: 3.2, boss: true },
  flower_dome_titan: { inner: "#a0d0c0", outer: "#2a6a5a", scale: 3.1, boss: true },
  // Pulau Hantu (Singapore — Ghost Island)
  pontianak: { inner: "#e0e0e8", outer: "#6a6a7a", scale: 1.3 },
  orang_minyak: { inner: "#5a5a5a", outer: "#101010", scale: 1.35 },
  hantu_air: { inner: "#a0c0d0", outer: "#2a4a5a", scale: 1.25 },
  pontianak_queen: { inner: "#f0f0f8", outer: "#7a7a8a", scale: 2.9, boss: true },
  penanggalan: { inner: "#e0a0a0", outer: "#5a1818", scale: 2.8, boss: true },
  // Sentosa (Singapore — capstone)
  otter_alpha: { inner: "#c0a070", outer: "#5a3a20", scale: 1.2 },
  giant_grouper: { inner: "#80b0a0", outer: "#2a5a4a", scale: 1.4 },
  resort_peacock: { inner: "#40c0c0", outer: "#1a5a6a", scale: 1.3 },
  sentosa_merlion: { inner: "#f0e8b0", outer: "#a07830", scale: 3.3, boss: true },
  leviathan: { inner: "#60a0c0", outer: "#0a3a5a", scale: 3.4, boss: true },
  // Kampong Glam (Singapore)
  bugis_corsair: { inner: "#d0b080", outer: "#5a3a20", scale: 1.3 },
  djinn: { inner: "#e0a060", outer: "#6a2810", scale: 1.35 },
  batik_serpent: { inner: "#d0a060", outer: "#5a3818", scale: 1.4 },
  sultan_jinn: { inner: "#f0b050", outer: "#6a2810", scale: 2.9, boss: true },
  naga_emas: { inner: "#f0d860", outer: "#7a5810", scale: 3.0, boss: true },
  // Marina Bay (Singapore)
  chrome_sentry: { inner: "#c0c8d0", outer: "#4a525c", scale: 1.4 },
  neon_wisp: { inner: "#80f0e0", outer: "#1a6a7a", scale: 1.1 },
  drone_swarm: { inner: "#b0c0d0", outer: "#3a4a5a", scale: 0.95 },
  skyline_colossus: { inner: "#c0d0e0", outer: "#3a4a6a", scale: 3.3, boss: true },
  spectra_dragon: { inner: "#a0e0f0", outer: "#1a5a7a", scale: 3.2, boss: true },
  // Jurong (Singapore)
  lab_slime: { inner: "#a0e0c0", outer: "#3a7a5a", scale: 1.0 },
  raptor: { inner: "#c0a060", outer: "#5a3a18", scale: 1.2 },
  pterodactyl: { inner: "#c0b090", outer: "#5a4a30", scale: 1.3 },
  t_rex: { inner: "#a0c070", outer: "#3a5a20", scale: 3.0, boss: true },
  mecha_dino: { inner: "#c0c8d0", outer: "#4a525c", scale: 3.1, boss: true },
  // Pulau Ubin (Singapore)
  wild_boar: { inner: "#b09070", outer: "#4a3020", scale: 1.2 },
  kampong_rooster: { inner: "#e0a040", outer: "#7a2818", scale: 1.0 },
  mangrove_crab: { inner: "#c08060", outer: "#5a2818", scale: 1.1 },
  boar_king: { inner: "#c0a080", outer: "#5a3a20", scale: 2.8, boss: true },
  mangrove_naga: { inner: "#80b890", outer: "#1a5a3a", scale: 2.9, boss: true },
  // Haw Par Villa (Singapore — Ten Courts of Hell)
  hell_judge: { inner: "#c0b0a0", outer: "#4a3a2a", scale: 1.4 },
  ox_head: { inner: "#90c0a0", outer: "#2a5a3a", scale: 1.5 },
  horse_face: { inner: "#e0b0a0", outer: "#5a2818", scale: 1.5 },
  yama_king: { inner: "#e06060", outer: "#3a0a0a", scale: 3.2, boss: true },
  tiger_spirit: { inner: "#f0a040", outer: "#6a2810", scale: 3.0, boss: true },
  // East Coast Park (Singapore)
  beach_crab: { inner: "#e08060", outer: "#7a2818", scale: 1.0 },
  seagull: { inner: "#f0f0f0", outer: "#9098a0", scale: 1.1 },
  sand_flea: { inner: "#d0c090", outer: "#6a5a30", scale: 0.85 },
  giant_stingray: { inner: "#90b0c0", outer: "#2a4a5a", scale: 2.8, boss: true },
  tidal_kraken: { inner: "#70b0c0", outer: "#1a4a5a", scale: 3.0, boss: true },
  // Fort Canning (Singapore)
  spice_sprite: { inner: "#c0e090", outer: "#5a7a30", scale: 1.1 },
  war_ghost: { inner: "#c0c8d0", outer: "#4a525c", scale: 1.3 },
  bunker_sentry: { inner: "#9aa090", outer: "#3a4030", scale: 1.4 },
  colonial_wraith: { inner: "#d0d0d8", outer: "#5a5a6a", scale: 2.7, boss: true },
  hill_sentinel: { inner: "#a0a890", outer: "#3a4230", scale: 3.0, boss: true },
  // Mount Faber (Singapore)
  cable_wraith: { inner: "#c0c8d0", outer: "#4a525c", scale: 1.3 },
  peak_eagle: { inner: "#d0d8e0", outer: "#5a6a7a", scale: 1.3 },
  stone_golem: { inner: "#a0a090", outer: "#3a3a30", scale: 1.4 },
  faber_titan: { inner: "#a0b0a0", outer: "#3a4a3a", scale: 3.1, boss: true },
  wind_djinn: { inner: "#b0e0e0", outer: "#2a6a6a", scale: 2.9, boss: true },
  // Changi (Singapore)
  pow_spirit: { inner: "#c0c8d0", outer: "#4a525c", scale: 1.3 },
  beach_ghoul: { inner: "#a0b090", outer: "#3a4a30", scale: 1.4 },
  jewel_drone: { inner: "#b0d8e0", outer: "#3a6a7a", scale: 1.2 },
  changi_revenant: { inner: "#d0d8e0", outer: "#4a5a6a", scale: 2.8, boss: true },
  vortex_guardian: { inner: "#80c0d0", outer: "#1a5a6a", scale: 3.1, boss: true },
  water_monitor: { inner: "#6a7a4a", outer: "#2a3a1a", scale: 1.5 },
  treetop_colugo: { inner: "#9a8a6a", outer: "#3a2e1a", scale: 1.3 },
  swamp_leech: { inner: "#7a4a5a", outer: "#2a1020", scale: 1.3 },
  treetop_warden: { inner: "#4faa5a", outer: "#1a4a24", scale: 3.0, boss: true },
  reservoir_naga: { inner: "#3fb08a", outer: "#0a4a3a", scale: 3.1, boss: true },
  festival_effigy: { inner: "#f0a040", outer: "#7a3a10", scale: 1.5 },
  deepavali_wisp: { inner: "#ffd860", outer: "#a05010", scale: 1.3 },
  saree_serpent: { inner: "#e05a80", outer: "#6a1030", scale: 1.5 },
  kali_avatar: { inner: "#5a3a6a", outer: "#1a0a24", scale: 3.2, boss: true },
  gopuram_guardian: { inner: "#e0a050", outer: "#6a3a10", scale: 3.2, boss: true },
  mall_mannequin: { inner: "#d0d0d8", outer: "#5a5a6a", scale: 1.5 },
  neon_phantom: { inner: "#c060f0", outer: "#3a0a5a", scale: 1.4 },
  holo_serpent: { inner: "#40d0e0", outer: "#0a4a6a", scale: 1.5 },
  ion_colossus: { inner: "#80e0ff", outer: "#1a3a6a", scale: 3.3, boss: true },
  orchard_specter: { inner: "#a040c0", outer: "#1a0824", scale: 3.3, boss: true },
  wetland_heron: { inner: "#e0e0d0", outer: "#7a7a5a", scale: 1.4 },
  fiddler_crab: { inner: "#e08040", outer: "#7a3a10", scale: 1.2 },
  marsh_terrapin: { inner: "#6a8a4a", outer: "#2a3a1a", scale: 1.4 },
  estuarine_titan: { inner: "#5a7a3a", outer: "#1a2a0a", scale: 2.9, boss: true },
  garuda_matriarch: { inner: "#d0a050", outer: "#5a3a10", scale: 3.0, boss: true },
  night_panther: { inner: "#3a3a4a", outer: "#0a0a14", scale: 1.6 },
  giant_flying_fox: { inner: "#5a3a2a", outer: "#1a0a08", scale: 1.5 },
  moonlit_moth: { inner: "#a0b0d0", outer: "#3a3a5a", scale: 1.3 },
  malayan_tiger_lord: { inner: "#e0a040", outer: "#3a2008", scale: 3.2, boss: true },
  mandai_naga: { inner: "#4a8a5a", outer: "#0a2414", scale: 3.2, boss: true },
  temple_tortoise: { inner: "#7a9a5a", outer: "#2a3a1a", scale: 1.5 },
  shrine_carp: { inner: "#e0a060", outer: "#7a3a10", scale: 1.3 },
  pilgrim_wisp: { inner: "#ffe0a0", outer: "#a07020", scale: 1.3 },
  kusu_tortoise_god: { inner: "#8ab060", outer: "#2a4a1a", scale: 3.0, boss: true },
  wishing_well_naga: { inner: "#50b0b0", outer: "#0a4a4a", scale: 3.0, boss: true },
  garden_swan: { inner: "#f0f0f8", outer: "#9a9aa8", scale: 1.3 },
  orchid_sprite: { inner: "#e070c0", outer: "#6a1a5a", scale: 1.2 },
  koi_spirit: { inner: "#f08040", outer: "#8a3010", scale: 1.3 },
  bandstand_golem: { inner: "#c0b070", outer: "#5a4a20", scale: 2.7, boss: true },
  swan_lake_naga: { inner: "#80c0e0", outer: "#1a5a7a", scale: 2.8, boss: true },
  battery_phantom: { inner: "#a0b0a0", outer: "#2a3a2a", scale: 1.3 },
  reef_lobster: { inner: "#e06040", outer: "#7a2010", scale: 1.3 },
  cliff_bat: { inner: "#6a5a4a", outer: "#1a120a", scale: 1.2 },
  coastal_gun_golem: { inner: "#8a8a7a", outer: "#3a3a2a", scale: 2.8, boss: true },
  dragon_teeth_wraith: { inner: "#b0c0c0", outer: "#2a3a3a", scale: 2.8, boss: true },
  coney_bull: { inner: "#e8e8e0", outer: "#7a6a5a", scale: 1.6 },
  casuarina_sprite: { inner: "#8ac060", outer: "#2a5a1a", scale: 1.2 },
  mudflat_crane: { inner: "#e0e0d8", outer: "#7a7a5a", scale: 1.4 },
  white_bull_king: { inner: "#f0f0e8", outer: "#8a7a6a", scale: 3.0, boss: true },
  driftwood_treant: { inner: "#9a8a5a", outer: "#3a2a14", scale: 3.0, boss: true },
  kopitiam_spirit: { inner: "#c0a070", outer: "#4a3010", scale: 1.3 },
  songbird_swarm: { inner: "#e0c060", outer: "#7a5a10", scale: 1.2 },
  back_alley_rat: { inner: "#7a6a5a", outer: "#2a1f14", scale: 1.3 },
  art_deco_golem: { inner: "#d0c0a0", outer: "#5a4a30", scale: 2.7, boss: true },
  market_wraith: { inner: "#a08090", outer: "#2a1a24", scale: 2.7, boss: true },
  kelong_crab: { inner: "#d07050", outer: "#6a2a10", scale: 1.3 },
  lalang_sprite: { inner: "#bcd070", outer: "#5a6a20", scale: 1.2 },
  waterway_egret: { inner: "#f0f0e8", outer: "#8a8a6a", scale: 1.4 },
  sand_quarry_golem: { inner: "#c0a878", outer: "#5a4424", scale: 2.9, boss: true },
  tilapia_titan: { inner: "#7a9a6a", outer: "#2a3a1a", scale: 2.9, boss: true },
  sandcastle_crab: { inner: "#e0c080", outer: "#8a6020", scale: 1.1 },
  park_squirrel: { inner: "#a07850", outer: "#3a2010", scale: 1.0 },
  kite_wisp: { inner: "#ffd0a0", outer: "#a06030", scale: 1.1 },
  mangrove_monitor: { inner: "#6a8a4a", outer: "#2a3a1a", scale: 2.4, boss: true },
  hedge_maze_golem: { inner: "#5a9a4a", outer: "#1a3a14", scale: 2.5, boss: true },
  turbine_sentinel: { inner: "#90b0c0", outer: "#2a4a5a", scale: 1.6 },
  spillway_wraith: { inner: "#80c0d0", outer: "#1a4a5a", scale: 1.4 },
  surge_elemental: { inner: "#60b0e0", outer: "#0a4a7a", scale: 1.5 },
  barrage_leviathan: { inner: "#3a90c0", outer: "#0a2a5a", scale: 3.4, boss: true },
  tempest_dragon: { inner: "#a0c0e0", outer: "#1a3a6a", scale: 3.4, boss: true },
};

export const DEFAULT_TEMPLATE = "poring";

// Build one texture per species up front (cheap canvas draws).
export function buildMonsterAppearances(): Record<string, MonsterAppearance> {
  const out: Record<string, MonsterAppearance> = {};
  for (const [id, d] of Object.entries(DEFS)) {
    const arch = ARCH[id] ?? "jelly";
    out[id] = {
      arch,
      texture: makePoringTexture(d.inner, d.outer),
      main: hex(d.outer),
      accent: hex(d.inner),
      scale: d.scale,
      boss: d.boss,
    };
  }
  return out;
}
