// Message kinds carried in the `t` field of every protocol message.
export enum MsgType {
  // client -> server
  Join = "join",
  MoveIntent = "move",
  AttackIntent = "attack",
  SkillIntent = "skill",
  JobAdvance = "jobAdvance",
  UseItem = "useItem",
  Equip = "equip",
  Unequip = "unequip",
  BuyItem = "buyItem",
  SellItem = "sellItem",
  StoreItem = "storeItem",
  RetrieveItem = "retrieveItem",
  PartyInvite = "partyInvite",
  PartyAccept = "partyAccept",
  PartyLeave = "partyLeave",
  CreateGuild = "createGuild",
  JoinGuild = "joinGuild",
  LeaveGuild = "leaveGuild",
  GuildStoreItem = "guildStoreItem",
  GuildRetrieveItem = "guildRetrieveItem",
  DuelRequest = "duelRequest",
  DuelAccept = "duelAccept",
  DuelDecline = "duelDecline",
  DuelCancel = "duelCancel",
  AcceptQuest = "acceptQuest",
  ClaimQuest = "claimQuest",
  AllocateStat = "allocateStat",
  LevelSkill = "levelSkill",
  UnlockRune = "unlockRune",
  RefineItem = "refineItem",
  EnchantItem = "enchantItem",
  ToggleEnchantLock = "toggleEnchantLock",
  SocketCard = "socketCard",
  UnsocketCard = "unsocketCard",
  EnterPortal = "enterPortal",
  NpcHeal = "npcHeal",
  Warp = "warp",
  Gather = "gather",
  Craft = "craft",
  EnterTower = "enterTower",
  ExchangeBrowse = "exchangeBrowse",
  ExchangeList = "exchangeList",
  ExchangeBuy = "exchangeBuy",
  ExchangeCancel = "exchangeCancel",
  Chat = "chat",
  Ping = "ping",
  // server -> client
  JoinAck = "joinAck",
  Spawn = "spawn",
  Despawn = "despawn",
  Snapshot = "snapshot",
  SelfSync = "self",
  Loot = "loot",
  PartyInviteRecv = "partyInviteRecv",
  PartyUpdate = "partyUpdate",
  GuildUpdate = "guildUpdate",
  DuelRequestRecv = "duelRequestRecv",
  DuelUpdate = "duelUpdate",
  TowerUpdate = "towerUpdate",
  MapChange = "mapChange",
  Defeated = "defeated",
  RefineResult = "refineResult",
  BossTelegraph = "bossTelegraph",
  SkillCast = "skillCast",
  DamageEvent = "damage",
  LevelUp = "levelUp",
  ChatBroadcast = "chatMsg",
  WorldState = "worldState",
  BossStatus = "bossStatus",
  ExchangeUpdate = "exchangeUpdate",
  Pong = "pong",
}

export enum EntityKind {
  Player = "player",
  Monster = "monster",
  Npc = "npc",
}

export enum MonsterAIState {
  Idle = "idle",
  Wander = "wander",
  Aggro = "aggro",
  Attack = "attack",
  Dead = "dead",
}

export enum JobId {
  Novice = "novice",
  Swordsman = "swordsman",
  Mage = "mage",
  Archer = "archer",
  Acolyte = "acolyte",
  Knight = "knight",
  Wizard = "wizard",
  Hunter = "hunter",
  Priest = "priest",
  RuneKnight = "rune_knight",
  HighWizard = "high_wizard",
  Sniper = "sniper",
  HighPriest = "high_priest",
  DragonKnight = "dragon_knight",
  ArchMage = "arch_mage",
  Windhawk = "windhawk",
  Cardinal = "cardinal",
  Thief = "thief",
  Merchant = "merchant",
  Assassin = "assassin",
  Blacksmith = "blacksmith",
  GuillotineCross = "guillotine_cross",
  Whitesmith = "whitesmith",
  ShadowCross = "shadow_cross",
  Mechanic = "mechanic",
  Crusader = "crusader",
  Paladin = "paladin",
  RoyalGuard = "royal_guard",
  Sage = "sage",
  Professor = "professor",
  Monk = "monk",
  Champion = "champion",
  Rogue = "rogue",
  Stalker = "stalker",
  Bard = "bard",
  Minstrel = "minstrel",
  Alchemist = "alchemist",
  Creator = "creator",
  Chronomancer = "chronomancer",
  DragonFist = "dragon_fist",
  PhantomDancer = "phantom_dancer",
  Maestro = "maestro",
  Begetter = "begetter",
}

export enum DamageKind {
  Physical = "physical",
  Magic = "magic",
}

export enum ItemType {
  Weapon = "weapon",
  Headgear = "headgear",
  Armor = "armor",
  Accessory = "accessory",
  Consumable = "consumable",
  Card = "card",
  Material = "material", // crafting/refine materials (ores, etc.)
}

export enum EquipSlot {
  Weapon = "weapon",
  Headgear = "headgear",
  Armor = "armor",
  Accessory = "accessory",
}

export enum StatusType {
  Slow = "slow", // reduced movement speed
  Stun = "stun", // cannot act
  Burn = "burn", // damage over time
}
