export interface QuestReward {
  exp: number;
  zeny: number;
  items?: Array<{ id: string; qty: number }>;
}

export interface Quest {
  id: string;
  name: string;
  desc: string;
  targetTemplate: string; // monster template id to slay
  targetName: string; // display name of the target
  count: number;
  requiredLevel: number;
  reward: QuestReward;
  repeatable?: boolean; // daily-style bounty: re-acceptable after turning in
}

// Kill-quest board offered by the town Guide. Ordered by difficulty.
export const QUESTS: Record<string, Quest> = {
  poring_purge: {
    id: "poring_purge",
    name: "Poring Purge",
    desc: "The fields are overrun. Thin the Poring population.",
    targetTemplate: "poring",
    targetName: "Poring",
    count: 10,
    requiredLevel: 1,
    reward: { exp: 120, zeny: 80, items: [{ id: "red_potion", qty: 3 }] },
  },
  fabre_fears: {
    id: "fabre_fears",
    name: "Fabre Fears",
    desc: "Fabres are nibbling the crops. Deal with them.",
    targetTemplate: "fabre",
    targetName: "Fabre",
    count: 8,
    requiredLevel: 3,
    reward: { exp: 220, zeny: 140, items: [{ id: "cotton_shirt", qty: 1 }] },
  },
  drop_the_drops: {
    id: "drop_the_drops",
    name: "Drop the Drops",
    desc: "Sweet Drops draw too many adventurers. Clear them out.",
    targetTemplate: "drops",
    targetName: "Drops",
    count: 8,
    requiredLevel: 5,
    reward: { exp: 360, zeny: 220, items: [{ id: "blue_potion", qty: 3 }] },
  },
  lunatic_hunt: {
    id: "lunatic_hunt",
    name: "Lunatic Hunt",
    desc: "Lunatics grow bold near the meadow. Hunt them down.",
    targetTemplate: "lunatic",
    targetName: "Lunatic",
    count: 6,
    requiredLevel: 8,
    reward: { exp: 600, zeny: 360, items: [{ id: "leather_armor", qty: 1 }] },
  },
  slay_the_king: {
    id: "slay_the_king",
    name: "Slay the King",
    desc: "The Poring King rules the northern arena. End its reign.",
    targetTemplate: "poring_king",
    targetName: "Poring King",
    count: 1,
    requiredLevel: 12,
    reward: { exp: 2500, zeny: 1500, items: [{ id: "ring_of_power", qty: 1 }] },
  },
  fabre_cull: {
    id: "fabre_cull",
    name: "Fabre Cull",
    desc: "More Fabres have hatched. Cull the swarm.",
    targetTemplate: "fabre",
    targetName: "Fabre",
    count: 12,
    requiredLevel: 2,
    reward: { exp: 280, zeny: 160, items: [{ id: "novice_knife", qty: 1 }] },
  },
  lunatic_purge: {
    id: "lunatic_purge",
    name: "Lunatic Purge",
    desc: "The meadow Lunatics breed too fast. Thin them out.",
    targetTemplate: "lunatic",
    targetName: "Lunatic",
    count: 12,
    requiredLevel: 6,
    reward: { exp: 800, zeny: 420, items: [{ id: "ring_of_power", qty: 1 }] },
  },
  zombie_cleanup: {
    id: "zombie_cleanup",
    name: "Zombie Cleanup",
    desc: "The undead shamble through Glast Heim. Put them to rest.",
    targetTemplate: "zombie",
    targetName: "Zombie",
    count: 12,
    requiredLevel: 15,
    reward: { exp: 3200, zeny: 1800, items: [{ id: "saint_robe", qty: 1 }] },
  },
  bone_collector: {
    id: "bone_collector",
    name: "Bone Collector",
    desc: "Skeletons guard the inner halls. Scatter their bones.",
    targetTemplate: "skeleton",
    targetName: "Skeleton",
    count: 12,
    requiredLevel: 18,
    reward: { exp: 4800, zeny: 2600, items: [{ id: "claymore", qty: 1 }] },
  },
  demon_slayer: {
    id: "demon_slayer",
    name: "Demon Slayer",
    desc: "Baphomet rules Glast Heim's depths. Banish the demon lord.",
    targetTemplate: "baphomet",
    targetName: "Baphomet",
    count: 1,
    requiredLevel: 28,
    reward: { exp: 15000, zeny: 9000, items: [{ id: "baphomet_horn", qty: 1 }] },
  },
  mirror_match: {
    id: "mirror_match",
    name: "Mirror Match",
    desc: "A Doppelganger haunts Geffen Tower, wearing other faces. Unmask it.",
    targetTemplate: "doppelganger",
    targetName: "Doppelganger",
    count: 1,
    requiredLevel: 40,
    reward: { exp: 9000, zeny: 6000, items: [{ id: "mage_staff", qty: 1 }] },
  },
  the_dark_illusion: {
    id: "the_dark_illusion",
    name: "The Dark Illusion",
    desc: "A Dark Illusion warps the Glast Heim Abyss. Dispel the phantom.",
    targetTemplate: "dark_illusion",
    targetName: "Dark Illusion",
    count: 1,
    requiredLevel: 108,
    reward: { exp: 200000, zeny: 110000, items: [{ id: "bloody_sword", qty: 1 }] },
  },
  golden_terror: {
    id: "golden_terror",
    name: "The Golden Terror",
    desc: "Gold Acidus hoards the Veins Canyon. Bring down the gilded dragon.",
    targetTemplate: "gold_acidus",
    targetName: "Gold Acidus",
    count: 1,
    requiredLevel: 78,
    reward: { exp: 54000, zeny: 31000, items: [{ id: "sand_spear", qty: 1 }] },
  },
  river_terror: {
    id: "river_terror",
    name: "Terror of the River",
    desc: "A Giant Anaconda devours Brasilis's fishers. Slay the river terror.",
    targetTemplate: "anaconda",
    targetName: "Giant Anaconda",
    count: 1,
    requiredLevel: 66,
    reward: { exp: 36000, zeny: 22000, items: [{ id: "machete", qty: 1 }] },
  },
  bridge_of_dreams: {
    id: "bridge_of_dreams",
    name: "Bridge of Dreams",
    desc: "Bungisngis blocks the Bifrost bridge with laughter and fists. Cross it.",
    targetTemplate: "bungisngis",
    targetName: "Bungisngis",
    count: 1,
    requiredLevel: 102,
    reward: { exp: 180000, zeny: 100000, items: [{ id: "fairy_bow", qty: 1 }] },
  },
  the_jade_warlord: {
    id: "the_jade_warlord",
    name: "The Jade Warlord",
    desc: "The Jade Warlord seizes Gonryun Shrine. Break his iron grip.",
    targetTemplate: "jade_warlord",
    targetName: "Jade Warlord",
    count: 1,
    requiredLevel: 92,
    reward: { exp: 100000, zeny: 58000, items: [{ id: "tachi", qty: 1 }] },
  },
  serpent_lord: {
    id: "serpent_lord",
    name: "The Serpent Lord",
    desc: "The Evil Snake Lord poisons Louyang's gardens. Sever the serpent.",
    targetTemplate: "evil_snake_lord",
    targetName: "Evil Snake Lord",
    count: 1,
    requiredLevel: 80,
    reward: { exp: 56000, zeny: 32000, items: [{ id: "serpent_spear", qty: 1 }] },
  },
  shell_breaker: {
    id: "shell_breaker",
    name: "Shell Breaker",
    desc: "The Turtle General fortifies the island. Crack his command.",
    targetTemplate: "turtle_general",
    targetName: "Turtle General",
    count: 1,
    requiredLevel: 72,
    reward: { exp: 52000, zeny: 30000, items: [{ id: "shell_blade", qty: 1 }] },
  },
  curse_of_osiris: {
    id: "curse_of_osiris",
    name: "Curse of Osiris",
    desc: "Osiris stirs in the Pyramid's depths. Break the pharaoh-god's curse.",
    targetTemplate: "osiris",
    targetName: "Osiris",
    count: 1,
    requiredLevel: 58,
    reward: { exp: 30000, zeny: 18000, items: [{ id: "ankh_staff", qty: 1 }] },
  },
  the_abysmal_knight: {
    id: "the_abysmal_knight",
    name: "The Abysmal Knight",
    desc: "An Abysmal Knight commands the Churchyard dead. Lay the crusader to rest.",
    targetTemplate: "abysmal_knight",
    targetName: "Abysmal Knight",
    count: 1,
    requiredLevel: 44,
    reward: { exp: 14000, zeny: 9000, items: [{ id: "knight_sword", qty: 1 }] },
  },
  orc_hero_hunt: {
    id: "orc_hero_hunt",
    name: "Slay the Orc Hero",
    desc: "The Orc Hero rallies the war camp. Cut off the head of the horde.",
    targetTemplate: "orc_hero",
    targetName: "Orc Hero",
    count: 1,
    requiredLevel: 38,
    reward: { exp: 11000, zeny: 7000, items: [{ id: "orc_axe", qty: 1 }] },
  },
  deep_dweller: {
    id: "deep_dweller",
    name: "The Deep Dweller",
    desc: "Phreeoni lurks in the Byalan depths. Hunt the gluttonous beast.",
    targetTemplate: "phreeoni",
    targetName: "Phreeoni",
    count: 1,
    requiredLevel: 24,
    reward: { exp: 6000, zeny: 4000, items: [{ id: "coral_blade", qty: 1 }] },
  },
  lord_of_flame: {
    id: "lord_of_flame",
    name: "Lord of Flame",
    desc: "Ifrit rages at the heart of Thor Volcano. Extinguish the fire lord.",
    targetTemplate: "ifrit",
    targetName: "Ifrit",
    count: 1,
    requiredLevel: 104,
    reward: { exp: 220000, zeny: 120000, items: [{ id: "magma_axe", qty: 1 }] },
  },
  witch_of_the_woods: {
    id: "witch_of_the_woods",
    name: "Witch of the Woods",
    desc: "Baba Yaga curses the Moscovia forest. Break her hold over it.",
    targetTemplate: "baba_yaga",
    targetName: "Baba Yaga",
    count: 1,
    requiredLevel: 84,
    reward: { exp: 90000, zeny: 52000, items: [{ id: "forest_garb", qty: 1 }] },
  },
  temple_guardian: {
    id: "temple_guardian",
    name: "Temple Guardian",
    desc: "Leak, the serpent, defiles Ayothaya's temple. Drive it from the ruins.",
    targetTemplate: "leak",
    targetName: "Leak",
    count: 1,
    requiredLevel: 78,
    reward: { exp: 70000, zeny: 40000, items: [{ id: "jade_spear", qty: 1 }] },
  },
  winter_warden: {
    id: "winter_warden",
    name: "Winter Warden",
    desc: "Garm, the frost wolf, prowls the Lutie snowfield. Bring it down.",
    targetTemplate: "garm",
    targetName: "Garm",
    count: 1,
    requiredLevel: 50,
    reward: { exp: 24000, zeny: 15000, items: [{ id: "frost_blade", qty: 1 }] },
  },
  the_last_samurai: {
    id: "the_last_samurai",
    name: "The Last Samurai",
    desc: "A vengeful Samurai Specter haunts Amatsu. Grant it peace by the blade.",
    targetTemplate: "samurai_specter",
    targetName: "Samurai Specter",
    count: 1,
    requiredLevel: 60,
    reward: { exp: 45000, zeny: 26000, items: [{ id: "katana", qty: 1 }] },
  },
  rest_in_peace: {
    id: "rest_in_peace",
    name: "Rest in Peace",
    desc: "The Fallen Bishop desecrates Niflheim. Send the heretic to the grave.",
    targetTemplate: "fallen_bishop",
    targetName: "Fallen Bishop",
    count: 1,
    requiredLevel: 92,
    reward: { exp: 120000, zeny: 70000, items: [{ id: "necro_staff", qty: 1 }] },
  },
  beach_patrol: {
    id: "beach_patrol",
    name: "Beach Patrol",
    desc: "Sandmen ambush travelers on Comodo's shore. Clear them.",
    targetTemplate: "sandman",
    targetName: "Sandman",
    count: 12,
    requiredLevel: 50,
    reward: { exp: 24000, zeny: 12000, items: [{ id: "tidal_shoes", qty: 1 }] },
  },
  jungle_rite: {
    id: "jungle_rite",
    name: "Jungle Rite",
    desc: "The Umbala Dryads stir. Calm the forest.",
    targetTemplate: "dryad",
    targetName: "Dryad",
    count: 12,
    requiredLevel: 62,
    reward: { exp: 40000, zeny: 20000, items: [{ id: "spirit_staff", qty: 1 }] },
  },
  iron_works: {
    id: "iron_works",
    name: "Iron Works",
    desc: "Einbroch's Metalings clog the factory. Scrap them.",
    targetTemplate: "metaling",
    targetName: "Metaling",
    count: 14,
    requiredLevel: 80,
    reward: { exp: 90000, zeny: 45000, items: [{ id: "dragon_slayer", qty: 1 }] },
  },
  end_of_memory: {
    id: "end_of_memory",
    name: "End of Memory",
    desc: "Atop Thanatos Tower waits the Memory of Thanatos. End it.",
    targetTemplate: "memory_of_thanatos",
    targetName: "Memory of Thanatos",
    count: 1,
    requiredLevel: 120,
    reward: { exp: 800000, zeny: 300000, items: [{ id: "fallen_angel_wing", qty: 1 }] },
  },
  desert_curse: {
    id: "desert_curse",
    name: "Curse of the Sands",
    desc: "Anubis stalk the Morocc dunes. Lay the jackals to rest.",
    targetTemplate: "anubis",
    targetName: "Anubis",
    count: 14,
    requiredLevel: 116,
    reward: { exp: 700000, zeny: 280000, items: [{ id: "desert_sabre", qty: 1 }] },
  },
  satan_slayer: {
    id: "satan_slayer",
    name: "Fall of Morocc",
    desc: "The demon Satan Morroc rules the desert. Banish it.",
    targetTemplate: "satan_morroc",
    targetName: "Satan Morroc",
    count: 1,
    requiredLevel: 124,
    reward: { exp: 1200000, zeny: 500000, items: [{ id: "morrigane_helm", qty: 1 }] },
  },
  bio_breach: {
    id: "bio_breach",
    name: "Containment Breach",
    desc: "The Bio Lab's experiments are loose. Purge the Wickebines.",
    targetTemplate: "wickebine",
    targetName: "Wickebine",
    count: 14,
    requiredLevel: 122,
    reward: { exp: 900000, zeny: 360000, items: [{ id: "bio_coat", qty: 1 }] },
  },
  abyssal_dive: {
    id: "abyssal_dive",
    name: "Into the Abyss",
    desc: "Ferus dragons nest at Abyss Lake. Thin the brood.",
    targetTemplate: "ferus",
    targetName: "Ferus",
    count: 14,
    requiredLevel: 126,
    reward: { exp: 1100000, zeny: 440000, items: [{ id: "dragon_scale_mail", qty: 1 }] },
  },
  world_serpent: {
    id: "world_serpent",
    name: "The World Serpent",
    desc: "Nidhoggr's Shadow coils at the bottom of the Abyss. End it all.",
    targetTemplate: "nidhoggr",
    targetName: "Nidhoggr's Shadow",
    count: 1,
    requiredLevel: 130,
    reward: { exp: 2000000, zeny: 800000, items: [{ id: "nidhoggr_eye", qty: 1 }] },
  },

  // ---- repeatable daily bounties (turn in and re-accept for steady income) ----
  bounty_porings: {
    id: "bounty_porings",
    name: "Daily Bounty: Porings",
    desc: "A standing order: clear Porings for the merchant guild.",
    targetTemplate: "poring",
    targetName: "Poring",
    count: 15,
    requiredLevel: 1,
    reward: { exp: 200, zeny: 300, items: [{ id: "red_potion", qty: 2 }] },
    repeatable: true,
  },
  bounty_skeletons: {
    id: "bounty_skeletons",
    name: "Daily Bounty: Skeletons",
    desc: "A standing order: scatter Glast Heim's skeletons.",
    targetTemplate: "skeleton",
    targetName: "Skeleton",
    count: 15,
    requiredLevel: 18,
    reward: { exp: 5000, zeny: 3000, items: [{ id: "blue_potion", qty: 3 }] },
    repeatable: true,
  },
  bounty_metalings: {
    id: "bounty_metalings",
    name: "Daily Bounty: Metalings",
    desc: "A standing order: recycle Einbroch's Metalings.",
    targetTemplate: "metaling",
    targetName: "Metaling",
    count: 15,
    requiredLevel: 80,
    reward: { exp: 110000, zeny: 60000, items: [{ id: "royal_feast", qty: 1 }] },
    repeatable: true,
  },
  bounty_anubis: {
    id: "bounty_anubis",
    name: "Daily Bounty: Ore Run",
    desc: "A standing order: hunt Anubis for refine ore.",
    targetTemplate: "anubis",
    targetName: "Anubis",
    count: 15,
    requiredLevel: 116,
    reward: { exp: 600000, zeny: 200000, items: [{ id: "oridecon", qty: 3 }, { id: "elunium", qty: 3 }] },
    repeatable: true,
  },
};

export function getQuest(id: string): Quest | undefined {
  return QUESTS[id];
}

export interface ActiveQuest {
  id: string;
  progress: number;
}

export interface QuestState {
  active: ActiveQuest[];
  completed: string[];
}
