import { Element } from "./elements.js";
import { DamageKind, JobId, StatusType } from "./enums.js";

export interface SkillEffect {
  type: StatusType;
  durationMs: number;
  magnitude?: number; // slow: speed multiplier; burn: fraction of MATK per tick
}

export interface SkillDef {
  id: string;
  name: string;
  job: JobId;
  hotkey: number; // 1-based slot
  spCost: number;
  cooldownMs: number;
  range: number;
  kind: DamageKind;
  power: number; // multiplier applied to ATK/MATK
  castMs?: number; // base cast time before the skill fires (0/undefined = instant)
  aoeRadius?: number; // if set, also hits enemies within this radius of the target
  heal?: boolean; // restores the caster's HP instead of dealing damage
  buff?: { stat: "atk" | "matk"; mult: number; durationMs: number }; // self-buff
  effect?: SkillEffect; // status applied to enemies hit
  element?: Element; // offensive element (defaults to Neutral)
  desc: string;
}

// Iconic-feeling starter skills per job. Damage is server-authoritative; the
// client uses the same defs for the skill bar, SP gating and cooldown display.
export const SKILLS: Record<string, SkillDef> = {
  first_aid: {
    id: "first_aid",
    name: "First Aid",
    job: JobId.Novice,
    hotkey: 1,
    spCost: 8,
    cooldownMs: 4000,
    range: 0,
    kind: DamageKind.Magic,
    power: 0,
    heal: true,
    desc: "Restore a small amount of HP.",
  },
  bash: {
    id: "bash",
    name: "Bash",
    job: JobId.Swordsman,
    hotkey: 1,
    spCost: 8,
    cooldownMs: 1600,
    range: 2.6,
    kind: DamageKind.Physical,
    power: 2.4,
    desc: "A heavy strike on a single target.",
  },
  magnum_break: {
    id: "magnum_break",
    name: "Magnum Break",
    job: JobId.Swordsman,
    hotkey: 2,
    spCost: 18,
    cooldownMs: 5000,
    range: 3.2,
    kind: DamageKind.Physical,
    power: 1.8,
    aoeRadius: 5,
    effect: { type: StatusType.Slow, durationMs: 2500, magnitude: 0.5 },
    desc: "Fiery area blast that slows enemies.",
  },
  fire_bolt: {
    id: "fire_bolt",
    name: "Fire Bolt",
    job: JobId.Mage,
    hotkey: 1,
    spCost: 12,
    cooldownMs: 1500,
    range: 11,
    kind: DamageKind.Magic,
    power: 2.6,
    effect: { type: StatusType.Burn, durationMs: 3000, magnitude: 0.25 },
    desc: "Hurl a bolt of fire that burns over time.",
  },
  thunder_storm: {
    id: "thunder_storm",
    name: "Thunder Storm",
    job: JobId.Mage,
    hotkey: 2,
    spCost: 24,
    cooldownMs: 5500,
    range: 11,
    kind: DamageKind.Magic,
    power: 1.9,
    aoeRadius: 5.5,
    effect: { type: StatusType.Stun, durationMs: 1200 },
    desc: "Call lightning that stuns enemies briefly.",
  },

  // ---- 2nd-job skills ----
  pierce: {
    id: "pierce",
    name: "Pierce",
    job: JobId.Knight,
    hotkey: 3,
    spCost: 14,
    cooldownMs: 1800,
    range: 2.8,
    kind: DamageKind.Physical,
    power: 3.4,
    desc: "Run a spear through a single foe.",
  },
  bowling_bash: {
    id: "bowling_bash",
    name: "Bowling Bash",
    job: JobId.Knight,
    hotkey: 4,
    spCost: 28,
    cooldownMs: 6000,
    range: 3.2,
    kind: DamageKind.Physical,
    power: 2.6,
    aoeRadius: 6,
    effect: { type: StatusType.Stun, durationMs: 1500 },
    desc: "Knock enemies around in a wide arc, stunning them.",
  },
  jupitel_thunder: {
    id: "jupitel_thunder",
    name: "Jupitel Thunder",
    job: JobId.Wizard,
    hotkey: 3,
    spCost: 22,
    cooldownMs: 2200,
    range: 12,
    kind: DamageKind.Magic,
    power: 3.8,
    desc: "A piercing bolt of wind and lightning.",
  },
  meteor_storm: {
    id: "meteor_storm",
    name: "Meteor Storm",
    job: JobId.Wizard,
    hotkey: 4,
    spCost: 40,
    cooldownMs: 8000,
    range: 12,
    kind: DamageKind.Magic,
    power: 2.8,
    aoeRadius: 7,
    effect: { type: StatusType.Burn, durationMs: 4000, magnitude: 0.3 },
    desc: "Rain meteors that scorch a wide area over time.",
  },

  // ---- self-buff skills ----
  battle_focus: {
    id: "battle_focus",
    name: "Battle Focus",
    job: JobId.Swordsman,
    hotkey: 5,
    spCost: 18,
    cooldownMs: 20000,
    range: 0,
    kind: DamageKind.Physical,
    power: 0,
    buff: { stat: "atk", mult: 1.3, durationMs: 15000 },
    desc: "Steel your resolve: +30% ATK for 15s.",
  },
  mystic_focus: {
    id: "mystic_focus",
    name: "Mystic Focus",
    job: JobId.Mage,
    hotkey: 5,
    spCost: 22,
    cooldownMs: 20000,
    range: 0,
    kind: DamageKind.Magic,
    power: 0,
    buff: { stat: "matk", mult: 1.3, durationMs: 15000 },
    desc: "Channel arcane power: +30% MATK for 15s.",
  },

  // ---- Archer / Hunter ----
  double_strafe: {
    id: "double_strafe",
    name: "Double Strafe",
    job: JobId.Archer,
    hotkey: 1,
    spCost: 10,
    cooldownMs: 1400,
    range: 11,
    kind: DamageKind.Physical,
    power: 2.8,
    desc: "Fire two arrows at a single target.",
  },
  arrow_shower: {
    id: "arrow_shower",
    name: "Arrow Shower",
    job: JobId.Archer,
    hotkey: 2,
    spCost: 20,
    cooldownMs: 5000,
    range: 11,
    kind: DamageKind.Physical,
    power: 1.9,
    aoeRadius: 5,
    desc: "Rain arrows over an area.",
  },
  blitz_beat: {
    id: "blitz_beat",
    name: "Blitz Beat",
    job: JobId.Hunter,
    hotkey: 3,
    spCost: 16,
    cooldownMs: 2000,
    range: 11,
    kind: DamageKind.Physical,
    power: 3.6,
    desc: "A falcon strikes a single foe.",
  },
  sharp_shooting: {
    id: "sharp_shooting",
    name: "Sharp Shooting",
    job: JobId.Hunter,
    hotkey: 4,
    spCost: 30,
    cooldownMs: 6000,
    range: 12,
    kind: DamageKind.Physical,
    power: 2.7,
    aoeRadius: 6,
    effect: { type: StatusType.Slow, durationMs: 2000, magnitude: 0.5 },
    desc: "A piercing volley that slows enemies.",
  },

  // ---- Acolyte / Priest ----
  heal: {
    id: "heal",
    name: "Heal",
    job: JobId.Acolyte,
    hotkey: 1,
    spCost: 14,
    cooldownMs: 2500,
    range: 0,
    kind: DamageKind.Magic,
    power: 0,
    heal: true,
    desc: "Restore a good amount of HP.",
  },
  holy_light: {
    id: "holy_light",
    name: "Holy Light",
    job: JobId.Acolyte,
    hotkey: 2,
    spCost: 14,
    cooldownMs: 1600,
    range: 10,
    kind: DamageKind.Magic,
    power: 2.6,
    desc: "Smite a single enemy with holy light.",
  },
  magnus_exorcismus: {
    id: "magnus_exorcismus",
    name: "Magnus Exorcismus",
    job: JobId.Priest,
    hotkey: 3,
    spCost: 38,
    cooldownMs: 7000,
    range: 11,
    kind: DamageKind.Magic,
    power: 2.6,
    aoeRadius: 6.5,
    desc: "Holy fire scorches an area.",
  },
  blessing: {
    id: "blessing",
    name: "Blessing",
    job: JobId.Priest,
    hotkey: 4,
    spCost: 24,
    cooldownMs: 20000,
    range: 0,
    kind: DamageKind.Magic,
    power: 0,
    buff: { stat: "matk", mult: 1.3, durationMs: 18000 },
    desc: "Bless yourself: +30% MATK for 18s.",
  },

  // ---- 3rd-job (transcendent) ultimates ----
  dragon_breath: {
    id: "dragon_breath",
    name: "Dragon Breath",
    job: JobId.RuneKnight,
    hotkey: 6,
    spCost: 45,
    cooldownMs: 6500,
    range: 7,
    kind: DamageKind.Physical,
    power: 3.4,
    aoeRadius: 7,
    effect: { type: StatusType.Burn, durationMs: 4000, magnitude: 0.3 },
    desc: "Exhale searing dragonfire around you.",
  },
  storm_gust: {
    id: "storm_gust",
    name: "Storm Gust",
    job: JobId.HighWizard,
    hotkey: 6,
    spCost: 55,
    cooldownMs: 8000,
    range: 12,
    kind: DamageKind.Magic,
    power: 3.2,
    aoeRadius: 8,
    effect: { type: StatusType.Slow, durationMs: 3000, magnitude: 0.4 },
    desc: "A freezing storm that batters and slows a wide area.",
  },
  falcon_assault: {
    id: "falcon_assault",
    name: "Falcon Assault",
    job: JobId.Sniper,
    hotkey: 5,
    spCost: 40,
    cooldownMs: 4500,
    range: 13,
    kind: DamageKind.Physical,
    power: 5.2,
    desc: "Command your falcon to devastate a single target.",
  },
  judex: {
    id: "judex",
    name: "Judex",
    job: JobId.HighPriest,
    hotkey: 5,
    spCost: 42,
    cooldownMs: 6000,
    range: 11,
    kind: DamageKind.Magic,
    power: 3.2,
    aoeRadius: 6.5,
    desc: "Holy judgment rains on an area.",
  },

  // ---- 4th-job ultimates ----
  storm_slash: {
    id: "storm_slash",
    name: "Storm Slash",
    job: JobId.DragonKnight,
    hotkey: 7,
    spCost: 70,
    cooldownMs: 7000,
    range: 7,
    kind: DamageKind.Physical,
    power: 5.5,
    aoeRadius: 7.5,
    desc: "A whirlwind of blades devastates everything nearby.",
  },
  crimson_rock: {
    id: "crimson_rock",
    name: "Crimson Rock",
    job: JobId.ArchMage,
    hotkey: 7,
    spCost: 85,
    cooldownMs: 8500,
    range: 13,
    kind: DamageKind.Magic,
    power: 5.0,
    aoeRadius: 8,
    effect: { type: StatusType.Burn, durationMs: 4000, magnitude: 0.35 },
    desc: "Summon a colossal meteor that scorches a huge area.",
  },
  gale_storm: {
    id: "gale_storm",
    name: "Gale Storm Arrow",
    job: JobId.Windhawk,
    hotkey: 6,
    spCost: 70,
    cooldownMs: 6000,
    range: 14,
    kind: DamageKind.Physical,
    power: 6.5,
    aoeRadius: 6,
    effect: { type: StatusType.Slow, durationMs: 2500, magnitude: 0.5 },
    desc: "A tempest of arrows that shreds and slows.",
  },
  adoramus: {
    id: "adoramus",
    name: "Adoramus",
    job: JobId.Cardinal,
    hotkey: 6,
    spCost: 80,
    cooldownMs: 7000,
    range: 12,
    kind: DamageKind.Magic,
    power: 5.2,
    aoeRadius: 7,
    effect: { type: StatusType.Stun, durationMs: 1500 },
    desc: "Divine lances smite and stun an area.",
  },

  // ---- Thief / Assassin ----
  envenom: {
    id: "envenom",
    name: "Envenom",
    job: JobId.Thief,
    hotkey: 1,
    spCost: 10,
    cooldownMs: 1600,
    range: 2.4,
    kind: DamageKind.Physical,
    power: 2.6,
    effect: { type: StatusType.Burn, durationMs: 3000, magnitude: 0.25 },
    desc: "Stab with a poisoned blade that festers over time.",
  },
  cloaking: {
    id: "cloaking",
    name: "Cloaking",
    job: JobId.Thief,
    hotkey: 2,
    spCost: 18,
    cooldownMs: 20000,
    range: 0,
    kind: DamageKind.Physical,
    power: 0,
    buff: { stat: "atk", mult: 1.3, durationMs: 15000 },
    desc: "Vanish and reappear behind your foe: +30% ATK for 15s.",
  },
  sonic_blow: {
    id: "sonic_blow",
    name: "Sonic Blow",
    job: JobId.Assassin,
    hotkey: 3,
    spCost: 20,
    cooldownMs: 2000,
    range: 2.6,
    kind: DamageKind.Physical,
    power: 4.2,
    desc: "A blinding flurry of blade strikes on a single foe.",
  },
  grimtooth: {
    id: "grimtooth",
    name: "Grimtooth",
    job: JobId.Assassin,
    hotkey: 4,
    spCost: 28,
    cooldownMs: 5500,
    range: 8,
    kind: DamageKind.Physical,
    power: 2.8,
    aoeRadius: 5,
    effect: { type: StatusType.Slow, durationMs: 2000, magnitude: 0.5 },
    desc: "Hurl a spread of throwing daggers that hobble enemies.",
  },
  cross_impact: {
    id: "cross_impact",
    name: "Cross Impact",
    job: JobId.GuillotineCross,
    hotkey: 5,
    spCost: 42,
    cooldownMs: 6000,
    range: 2.8,
    kind: DamageKind.Physical,
    power: 5.2,
    effect: { type: StatusType.Burn, durationMs: 4000, magnitude: 0.3 },
    desc: "A venomous cross-strike that ruptures a single target.",
  },
  soul_breaker: {
    id: "soul_breaker",
    name: "Soul Breaker",
    job: JobId.ShadowCross,
    hotkey: 6,
    spCost: 75,
    cooldownMs: 7000,
    range: 3.0,
    kind: DamageKind.Physical,
    power: 6.5,
    effect: { type: StatusType.Stun, durationMs: 1500 },
    desc: "Shatter your target's soul with a piercing execution strike.",
  },

  // ---- Merchant / Blacksmith ----
  mammonite: {
    id: "mammonite",
    name: "Mammonite",
    job: JobId.Merchant,
    hotkey: 1,
    spCost: 10,
    cooldownMs: 1600,
    range: 2.4,
    kind: DamageKind.Physical,
    power: 2.4,
    desc: "Slam a foe with a coin-weighted mace.",
  },
  cart_swing: {
    id: "cart_swing",
    name: "Cart Swing",
    job: JobId.Merchant,
    hotkey: 2,
    spCost: 18,
    cooldownMs: 4500,
    range: 2.6,
    kind: DamageKind.Physical,
    power: 1.8,
    aoeRadius: 4,
    desc: "Swing your loaded cart through a cluster of foes.",
  },
  cart_revolution: {
    id: "cart_revolution",
    name: "Cart Revolution",
    job: JobId.Blacksmith,
    hotkey: 3,
    spCost: 30,
    cooldownMs: 5500,
    range: 3,
    kind: DamageKind.Physical,
    power: 2.7,
    aoeRadius: 5.5,
    desc: "Detonate your cart's cargo in a wide blast.",
  },
  adrenaline_rush: {
    id: "adrenaline_rush",
    name: "Adrenaline Rush",
    job: JobId.Blacksmith,
    hotkey: 4,
    spCost: 24,
    cooldownMs: 20000,
    range: 0,
    kind: DamageKind.Physical,
    power: 0,
    buff: { stat: "atk", mult: 1.3, durationMs: 15000 },
    desc: "Adrenaline surges: +30% ATK for 15s.",
  },
  meltdown: {
    id: "meltdown",
    name: "Meltdown",
    job: JobId.Whitesmith,
    hotkey: 5,
    spCost: 44,
    cooldownMs: 6500,
    range: 3.2,
    kind: DamageKind.Physical,
    power: 3.4,
    aoeRadius: 6.5,
    effect: { type: StatusType.Burn, durationMs: 4000, magnitude: 0.3 },
    desc: "Melt your weapon's temper into a wave of molten force.",
  },
  axe_tornado: {
    id: "axe_tornado",
    name: "Axe Tornado",
    job: JobId.Mechanic,
    hotkey: 6,
    spCost: 78,
    cooldownMs: 7000,
    range: 3.4,
    kind: DamageKind.Physical,
    power: 5.8,
    aoeRadius: 7,
    desc: "Spin into a tornado of axe blades that shreds everything nearby.",
  },

  // ---- Crusader / Paladin / Royal Guard ----
  shield_charge: {
    id: "shield_charge",
    name: "Shield Charge",
    job: JobId.Crusader,
    hotkey: 3,
    spCost: 16,
    cooldownMs: 2000,
    range: 2.8,
    kind: DamageKind.Physical,
    power: 3.2,
    desc: "Slam a foe with your shield, closing the gap in an instant.",
  },
  grand_cross: {
    id: "grand_cross",
    name: "Grand Cross",
    job: JobId.Crusader,
    hotkey: 4,
    spCost: 30,
    cooldownMs: 5500,
    range: 3,
    kind: DamageKind.Physical,
    power: 2.4,
    aoeRadius: 5.5,
    desc: "Detonate a holy cross beneath your feet, searing all nearby.",
  },
  shield_chain: {
    id: "shield_chain",
    name: "Shield Chain",
    job: JobId.Paladin,
    hotkey: 6,
    spCost: 44,
    cooldownMs: 6000,
    range: 2.8,
    kind: DamageKind.Physical,
    power: 5.4,
    desc: "A relentless flurry of shield strikes on a single foe.",
  },
  overbrand: {
    id: "overbrand",
    name: "Overbrand",
    job: JobId.RoyalGuard,
    hotkey: 7,
    spCost: 72,
    cooldownMs: 7000,
    range: 3,
    kind: DamageKind.Physical,
    power: 5.8,
    aoeRadius: 7,
    desc: "A wide, crashing cleave that levels everything in front of you.",
  },

  // ---- Sage / Professor ----
  arcane_lance: {
    id: "arcane_lance",
    name: "Arcane Lance",
    job: JobId.Sage,
    hotkey: 3,
    spCost: 20,
    cooldownMs: 2000,
    range: 11,
    kind: DamageKind.Magic,
    power: 3.6,
    desc: "A lance of raw arcane force skewers a single target.",
  },
  dispell_wave: {
    id: "dispell_wave",
    name: "Dispell Wave",
    job: JobId.Sage,
    hotkey: 4,
    spCost: 28,
    cooldownMs: 5500,
    range: 11,
    kind: DamageKind.Magic,
    power: 2.0,
    aoeRadius: 5.5,
    effect: { type: StatusType.Slow, durationMs: 2500, magnitude: 0.5 },
    desc: "A draining wave that saps enemies' vigor and slows them.",
  },
  grand_sage_nova: {
    id: "grand_sage_nova",
    name: "Grand Sage Nova",
    job: JobId.Professor,
    hotkey: 6,
    spCost: 52,
    cooldownMs: 7000,
    range: 12,
    kind: DamageKind.Magic,
    power: 3.4,
    aoeRadius: 7,
    effect: { type: StatusType.Stun, durationMs: 1400 },
    desc: "A pulse of overloaded arcana that stuns everything it touches.",
  },

  // ---- Monk / Champion ----
  chain_combo: {
    id: "chain_combo",
    name: "Chain Combo",
    job: JobId.Monk,
    hotkey: 3,
    spCost: 16,
    cooldownMs: 1800,
    range: 2.4,
    kind: DamageKind.Physical,
    power: 3.8,
    desc: "A blistering chain of unarmed strikes on a single foe.",
  },
  tiger_palm: {
    id: "tiger_palm",
    name: "Tiger Palm",
    job: JobId.Monk,
    hotkey: 4,
    spCost: 26,
    cooldownMs: 5000,
    range: 2.6,
    kind: DamageKind.Physical,
    power: 2.2,
    aoeRadius: 5,
    desc: "A sweeping palm strike that staggers everyone nearby.",
  },
  asura_strike: {
    id: "asura_strike",
    name: "Asura Strike",
    job: JobId.Champion,
    hotkey: 6,
    spCost: 90,
    cooldownMs: 8000,
    range: 2.8,
    kind: DamageKind.Physical,
    power: 6.5,
    desc: "Channel every last drop of SP into a single, world-shaking blow.",
  },

  // ---- Rogue / Stalker ----
  raid: {
    id: "raid",
    name: "Raid",
    job: JobId.Rogue,
    hotkey: 3,
    spCost: 22,
    cooldownMs: 5000,
    range: 8,
    kind: DamageKind.Physical,
    power: 2.6,
    aoeRadius: 5,
    desc: "A hail of thrown blades scatters across a wide area.",
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    job: JobId.Rogue,
    hotkey: 4,
    spCost: 18,
    cooldownMs: 2000,
    range: 2.6,
    kind: DamageKind.Physical,
    power: 4.2,
    desc: "Slip behind a foe for a vicious, exposed strike.",
  },
  shadow_reaper: {
    id: "shadow_reaper",
    name: "Shadow Reaper",
    job: JobId.Stalker,
    hotkey: 6,
    spCost: 58,
    cooldownMs: 6500,
    range: 2.8,
    kind: DamageKind.Physical,
    power: 5.6,
    desc: "Strike from the gathered dark itself, reaping a single foe.",
  },

  // ---- Bard / Minstrel ----
  melody_strike: {
    id: "melody_strike",
    name: "Melody Strike",
    job: JobId.Bard,
    hotkey: 3,
    spCost: 14,
    cooldownMs: 1600,
    range: 11,
    kind: DamageKind.Physical,
    power: 3.4,
    desc: "A resonant chord fired like an arrow at a single foe.",
  },
  battle_hymn: {
    id: "battle_hymn",
    name: "Battle Hymn",
    job: JobId.Bard,
    hotkey: 4,
    spCost: 20,
    cooldownMs: 20000,
    range: 0,
    kind: DamageKind.Physical,
    power: 0,
    buff: { stat: "atk", mult: 1.3, durationMs: 15000 },
    desc: "Strike up a rousing hymn: +30% ATK for 15s.",
  },
  severe_rainstorm: {
    id: "severe_rainstorm",
    name: "Severe Rainstorm",
    job: JobId.Minstrel,
    hotkey: 6,
    spCost: 50,
    cooldownMs: 6500,
    range: 12,
    kind: DamageKind.Physical,
    power: 5.0,
    aoeRadius: 6.5,
    effect: { type: StatusType.Stun, durationMs: 1300 },
    desc: "A disorienting downpour of arrows that stuns everyone caught in it.",
  },

  // ---- Alchemist / Creator ----
  acid_bomb: {
    id: "acid_bomb",
    name: "Acid Bomb",
    job: JobId.Alchemist,
    hotkey: 3,
    spCost: 20,
    cooldownMs: 2000,
    range: 9,
    kind: DamageKind.Magic,
    power: 3.6,
    desc: "Hurl a flask of corrosive acid at a single target.",
  },
  bio_explosion: {
    id: "bio_explosion",
    name: "Bio Explosion",
    job: JobId.Alchemist,
    hotkey: 4,
    spCost: 30,
    cooldownMs: 5500,
    range: 9,
    kind: DamageKind.Magic,
    power: 2.2,
    aoeRadius: 5,
    effect: { type: StatusType.Burn, durationMs: 3500, magnitude: 0.25 },
    desc: "A volatile brew that bursts into a caustic, burning cloud.",
  },
  plague_flask: {
    id: "plague_flask",
    name: "Plague Flask",
    job: JobId.Creator,
    hotkey: 6,
    spCost: 54,
    cooldownMs: 7000,
    range: 10,
    kind: DamageKind.Magic,
    power: 4.8,
    aoeRadius: 7,
    effect: { type: StatusType.Burn, durationMs: 4000, magnitude: 0.35 },
    desc: "Shatter a flask of engineered plague across a wide area.",
  },
};

// Tag elemental skills (everything else stays Neutral). Lets the combat chart
// reward hitting a monster's elemental weakness.
const SKILL_ELEMENTS: Record<string, Element> = {
  fire_bolt: Element.Fire,
  meteor_storm: Element.Fire,
  crimson_rock: Element.Fire,
  magnum_break: Element.Fire,
  dragon_breath: Element.Fire,
  thunder_storm: Element.Wind,
  jupitel_thunder: Element.Wind,
  gale_storm: Element.Wind,
  storm_slash: Element.Wind,
  storm_gust: Element.Water,
  holy_light: Element.Holy,
  magnus_exorcismus: Element.Holy,
  judex: Element.Holy,
  adoramus: Element.Holy,
  sonic_blow: Element.Shadow,
  grimtooth: Element.Shadow,
  cross_impact: Element.Shadow,
  soul_breaker: Element.Shadow,
  meltdown: Element.Fire,
  grand_cross: Element.Holy,
  shadow_reaper: Element.Shadow,
};
for (const [id, el] of Object.entries(SKILL_ELEMENTS)) {
  if (SKILLS[id]) SKILLS[id].element = el;
}

export const SKILLS_BY_JOB: Record<JobId, SkillDef[]> = {
  [JobId.Novice]: [SKILLS.first_aid],
  [JobId.Swordsman]: [SKILLS.bash, SKILLS.magnum_break, SKILLS.battle_focus],
  [JobId.Mage]: [SKILLS.fire_bolt, SKILLS.thunder_storm, SKILLS.mystic_focus],
  [JobId.Archer]: [SKILLS.double_strafe, SKILLS.arrow_shower],
  [JobId.Acolyte]: [SKILLS.heal, SKILLS.holy_light],
  // 2nd jobs keep their 1st-job kit and gain new skills.
  [JobId.Knight]: [SKILLS.bash, SKILLS.magnum_break, SKILLS.pierce, SKILLS.bowling_bash, SKILLS.battle_focus],
  [JobId.Wizard]: [SKILLS.fire_bolt, SKILLS.thunder_storm, SKILLS.jupitel_thunder, SKILLS.meteor_storm, SKILLS.mystic_focus],
  [JobId.Hunter]: [SKILLS.double_strafe, SKILLS.arrow_shower, SKILLS.blitz_beat, SKILLS.sharp_shooting],
  [JobId.Priest]: [SKILLS.heal, SKILLS.holy_light, SKILLS.magnus_exorcismus, SKILLS.blessing],
  // 3rd jobs keep their 2nd-job kit and gain an ultimate.
  [JobId.RuneKnight]: [SKILLS.bash, SKILLS.magnum_break, SKILLS.pierce, SKILLS.bowling_bash, SKILLS.battle_focus, SKILLS.dragon_breath],
  [JobId.HighWizard]: [SKILLS.fire_bolt, SKILLS.thunder_storm, SKILLS.jupitel_thunder, SKILLS.meteor_storm, SKILLS.mystic_focus, SKILLS.storm_gust],
  [JobId.Sniper]: [SKILLS.double_strafe, SKILLS.arrow_shower, SKILLS.blitz_beat, SKILLS.sharp_shooting, SKILLS.falcon_assault],
  [JobId.HighPriest]: [SKILLS.heal, SKILLS.holy_light, SKILLS.magnus_exorcismus, SKILLS.blessing, SKILLS.judex],
  // 4th jobs keep their 3rd-job kit and gain a powerful ultimate.
  [JobId.DragonKnight]: [SKILLS.bash, SKILLS.magnum_break, SKILLS.pierce, SKILLS.bowling_bash, SKILLS.battle_focus, SKILLS.dragon_breath, SKILLS.storm_slash],
  [JobId.ArchMage]: [SKILLS.fire_bolt, SKILLS.thunder_storm, SKILLS.jupitel_thunder, SKILLS.meteor_storm, SKILLS.mystic_focus, SKILLS.storm_gust, SKILLS.crimson_rock],
  [JobId.Windhawk]: [SKILLS.double_strafe, SKILLS.arrow_shower, SKILLS.blitz_beat, SKILLS.sharp_shooting, SKILLS.falcon_assault, SKILLS.gale_storm],
  [JobId.Cardinal]: [SKILLS.heal, SKILLS.holy_light, SKILLS.magnus_exorcismus, SKILLS.blessing, SKILLS.judex, SKILLS.adoramus],
  // ---- Thief family ----
  [JobId.Thief]: [SKILLS.envenom, SKILLS.cloaking],
  [JobId.Assassin]: [SKILLS.envenom, SKILLS.cloaking, SKILLS.sonic_blow, SKILLS.grimtooth],
  [JobId.GuillotineCross]: [SKILLS.envenom, SKILLS.cloaking, SKILLS.sonic_blow, SKILLS.grimtooth, SKILLS.cross_impact],
  [JobId.ShadowCross]: [
    SKILLS.envenom,
    SKILLS.cloaking,
    SKILLS.sonic_blow,
    SKILLS.grimtooth,
    SKILLS.cross_impact,
    SKILLS.soul_breaker,
  ],
  // ---- Merchant family ----
  [JobId.Merchant]: [SKILLS.mammonite, SKILLS.cart_swing],
  [JobId.Blacksmith]: [SKILLS.mammonite, SKILLS.cart_swing, SKILLS.cart_revolution, SKILLS.adrenaline_rush],
  [JobId.Whitesmith]: [
    SKILLS.mammonite,
    SKILLS.cart_swing,
    SKILLS.cart_revolution,
    SKILLS.adrenaline_rush,
    SKILLS.meltdown,
  ],
  [JobId.Mechanic]: [
    SKILLS.mammonite,
    SKILLS.cart_swing,
    SKILLS.cart_revolution,
    SKILLS.adrenaline_rush,
    SKILLS.meltdown,
    SKILLS.axe_tornado,
  ],
  // ---- Crusader family (Swordsman's other branch) ----
  [JobId.Crusader]: [SKILLS.bash, SKILLS.magnum_break, SKILLS.battle_focus, SKILLS.shield_charge, SKILLS.grand_cross],
  [JobId.Paladin]: [
    SKILLS.bash,
    SKILLS.magnum_break,
    SKILLS.battle_focus,
    SKILLS.shield_charge,
    SKILLS.grand_cross,
    SKILLS.shield_chain,
  ],
  [JobId.RoyalGuard]: [
    SKILLS.bash,
    SKILLS.magnum_break,
    SKILLS.battle_focus,
    SKILLS.shield_charge,
    SKILLS.grand_cross,
    SKILLS.shield_chain,
    SKILLS.overbrand,
  ],
  // ---- Sage family (Mage's other branch) ----
  [JobId.Sage]: [SKILLS.fire_bolt, SKILLS.thunder_storm, SKILLS.mystic_focus, SKILLS.arcane_lance, SKILLS.dispell_wave],
  [JobId.Professor]: [
    SKILLS.fire_bolt,
    SKILLS.thunder_storm,
    SKILLS.mystic_focus,
    SKILLS.arcane_lance,
    SKILLS.dispell_wave,
    SKILLS.grand_sage_nova,
  ],
  // ---- Monk family (Acolyte's other branch) ----
  [JobId.Monk]: [SKILLS.heal, SKILLS.holy_light, SKILLS.chain_combo, SKILLS.tiger_palm],
  [JobId.Champion]: [SKILLS.heal, SKILLS.holy_light, SKILLS.chain_combo, SKILLS.tiger_palm, SKILLS.asura_strike],
  // ---- Rogue family (Thief's other branch) ----
  [JobId.Rogue]: [SKILLS.envenom, SKILLS.cloaking, SKILLS.raid, SKILLS.backstab],
  [JobId.Stalker]: [
    SKILLS.envenom,
    SKILLS.cloaking,
    SKILLS.raid,
    SKILLS.backstab,
    SKILLS.shadow_reaper,
  ],
  // ---- Bard family (Archer's other branch) ----
  [JobId.Bard]: [SKILLS.double_strafe, SKILLS.arrow_shower, SKILLS.melody_strike, SKILLS.battle_hymn],
  [JobId.Minstrel]: [
    SKILLS.double_strafe,
    SKILLS.arrow_shower,
    SKILLS.melody_strike,
    SKILLS.battle_hymn,
    SKILLS.severe_rainstorm,
  ],
  // ---- Alchemist family (Merchant's other branch) ----
  [JobId.Alchemist]: [SKILLS.mammonite, SKILLS.cart_swing, SKILLS.acid_bomb, SKILLS.bio_explosion],
  [JobId.Creator]: [
    SKILLS.mammonite,
    SKILLS.cart_swing,
    SKILLS.acid_bomb,
    SKILLS.bio_explosion,
    SKILLS.plague_flask,
  ],
};

// Base cast times (ms) for the heavier magic nukes and ranged volleys. Melee
// strikes, buffs and heals stay instant. Cast time is shortened by DEX (below).
const CAST_TIMES: Record<string, number> = {
  fire_bolt: 600,
  thunder_storm: 900,
  jupitel_thunder: 700,
  meteor_storm: 1500,
  storm_gust: 1400,
  crimson_rock: 1600,
  holy_light: 450,
  magnus_exorcismus: 1300,
  judex: 800,
  adoramus: 1200,
  sharp_shooting: 700,
  arcane_lance: 650,
  dispell_wave: 950,
  grand_sage_nova: 1300,
  acid_bomb: 550,
  bio_explosion: 900,
  plague_flask: 1250,
  severe_rainstorm: 750,
};
for (const [id, ms] of Object.entries(CAST_TIMES)) {
  if (SKILLS[id]) SKILLS[id].castMs = ms;
}

// DEX shortens cast time (classic RO feel): each point trims it, down to a 25%
// floor. A DEX-stacked caster fires noticeably faster.
export function effectiveCastMs(def: SkillDef, dex: number): number {
  const base = def.castMs ?? 0;
  if (base <= 0) return 0;
  const factor = Math.max(0.25, 1 - dex / 120);
  return Math.round(base * factor);
}

export function getSkill(id: string): SkillDef | undefined {
  return SKILLS[id];
}

// Skills can be leveled 1..SKILL_MAX_LEVEL; power and SP cost scale with level.
export const SKILL_MAX_LEVEL = 5;

export function skillPower(def: SkillDef, level: number): number {
  return def.power * (1 + 0.25 * (Math.max(1, level) - 1));
}

export function skillSpCost(def: SkillDef, level: number): number {
  return Math.round(def.spCost * (1 + 0.1 * (Math.max(1, level) - 1)));
}

// Leveling a skill also trims its cooldown (down to a 30% reduction) so a maxed
// skill chains noticeably faster.
export function skillCooldownMs(def: SkillDef, level: number): number {
  return Math.round(def.cooldownMs * Math.max(0.7, 1 - 0.05 * (Math.max(1, level) - 1)));
}

// …and lengthens any crowd-control / DoT it applies (slow, stun, burn).
export function skillEffectDurationMs(baseMs: number, level: number): number {
  return Math.round(baseMs * (1 + 0.12 * (Math.max(1, level) - 1)));
}

// A short global lock after using any skill (classic RO "after-cast delay"),
// shortened by AGI down to a floor — agile characters chain skills faster.
export function afterCastDelayMs(agi: number): number {
  return Math.max(120, Math.round(420 - agi * 2.6));
}

// A skill is usable by a job if it appears in that job's kit (covers inherited
// 1st-job skills on 2nd jobs).
export function jobHasSkill(job: JobId, skillId: string): boolean {
  return (SKILLS_BY_JOB[job] ?? []).some((s) => s.id === skillId);
}
